### ISSUE TITLE
Mock NetworkBackend

### ISSUE THREAD

**Issue by danielSanchezQ** [logos-co/nomos-node#31]
For some testing purposes it would be nice to have a mock network module that is configurable.

There are different mocking versions that we could have:

- Preconfigured message stack
    - We could load a stack of messages that would arrive in direct order.
    - Optionally randomly selected messages (or weighted)
- Other idea is to use some kind of backend service like a redis (maybe embedded?) that replicates locally what waku does.

## Tasks

- [ ] Mock network backend
    - [ ] Preloaded stack version
    - [ ] Optionally service based version 
- [ ] Consensus network adapter if needed
- [ ] Mempool network adapter if needed

**Comment by bitcoinbrisbane** [comment]
Is this still open
