### ISSUE TITLE
Carnot execution simulation application

### ISSUE THREAD

**Issue by danielSanchezQ** [logos-co/nomos-node#92]
We need to be able to simulate execution times based on different parameters. The simulation app **should not** actually execute consensus, but black-box it over custom configurable execution times. 

Current base effort is done at #90. But this is just a start point and may/should change. It also have things that need to be done.

## Tasks:
- [x] Configuration (taken from IO)
    - [x] Networking cost should be configurable (fixed or ranged).
    - [x] Let user configure node steps 
- [x] Regions should be configurable as well
- [x] Overlay is just implemented for `Flat`, and takes no settings. We should implement a binary tree overlay distribution that is configurable over the size of the committees.
     - [ ] Tree overlay configuration should be taken from IO.
- [ ] Carnot execution with the runner must be exhaustively tested. **We need to make sure output simulation data it is what should be**
    - [ ] Use different config files to create multiple testcases for runner
    - [ ] Add network drop unit tests
- [ ] Make network wait maximum delay if a message gets dropped. https://github.com/logos-co/nomos-research/pull/90#discussion_r1129216403

- [ ] Implement Carnot node
    - [x] #168
    - [x] #169

## Chores

- [x]  `CommitteeId` and `NodeId` are just type aliases, it lead to a bug where we were mixing them. Make them actual wrapper types to avoid this. #104 

## Apps

- [ ] CLI 
- [ ] WASM web app
